export const columns = [
    { field: "empId", headerName: "ID", width: 150 },
    {
        field: "firstName",
        headerName: "First name",
        width: 150,
        // editable: true,
    },
    {
        field: "lastName",
        headerName: "Last name",
        width: 150,
        // editable: true,
    },
    {
        field: "salary",
        headerName: "Salary",
        width: 150,
        // editable: true,
    },
    {
        field: "fromDate",
        headerName: "Start Date",
        width: 150,
        // editable: true,
    },
    {
        field: "endDate",
        headerName: "End Date",
        width: 150,
        // editable: true,
    },
    {
        field: "position",
        headerName: "Position",
        width: 150,
        // editable: true,
    },
    {
        field: "role",
        headerName: "Role",
        width: 100,
        // editable: true,
    },
    {
        field: "age",
        headerName: "Age",
        type: "number",
        width: 100,
        // editable: true,
    },
    {
        field: "gender",
        headerName: "Gender",
        type: "string",
        width: 100,
    },
    {
        field: "edit",
        headerName: "Edit",
        type: "string",
        width: 100,
    },
];

export const employees = [
    { id: 1, empId: "AGLA.ST.001", lastName: "Snow", firstName: "Jon", age: 35, gender: "M" },
    {
        id: 2,
        empId: "AGLA.ST.002",
        lastName: "Lannister",
        firstName: "Cersei",
        age: 42,
        gender: "F",
    },
    {
        id: 3,
        empId: "AGLA.ST.003",
        lastName: "Lannister",
        firstName: "Jaime",
        age: 45,
        gender: "M",
    },
    { id: 4, empId: "AGLA.ST.004", lastName: "Stark", firstName: "Arya", age: 16, gender: "F" },
    {
        id: 5,
        empId: "AGLA.ST.005",
        lastName: "Targaryen",
        firstName: "Daenerys",
        age: null,
        gender: "M",
    },
    { id: 6, empId: "AGLA.ST.006", lastName: "Melisandre", firstName: null, age: 150, gender: "F" },
    {
        id: 7,
        empId: "AGLA.ST.007",
        lastName: "Clifford",
        firstName: "Ferrara",
        age: 44,
        gender: "M",
    },
    {
        id: 8,
        empId: "AGLA.ST.008",
        lastName: "Frances",
        firstName: "Rossini",
        age: 36,
        gender: "M",
    },
    { id: 9, empId: "AGLA.ST.009", lastName: "Roxie", firstName: "Harvey", age: 65, gender: "F" },
];
