export const departments = [
    { name: "Vault Basement", key: 1 },
    { name: "Vault Mezzanine", key: 2 },
    { name: "Vault Ground", key: 3 },
    { name: "Verification/CSR", key: 4 },
    { name: "Registration", key: 5 },
    { name: "Marriage", key: 6 },
    { name: "Insertions", key: 7 },
    { name: "Mail-In Unit", key: 8 },
    { name: "Admin Registry", key: 9 },
    { name: "Binders", key: 10 },
    { name: "Civil Data Entry", key: 11 },
    { name: "Deeds", key: 12 },
    { name: "Certified Copies", key: 13 },
    { name: "Land Registry", key: 14 },
    { name: "Data Entry", key: 15 },
    { name: "RG", key: 16 },
    { name: "Project Implementation Unit", key: 17 },
    { name: "Scanning", key: 18 },
    { name: "Compliance", key: 19 },
    { name: "Legal Services", key: 20 },
    { name: "Online Registry", key: 21 },
    { name: "Communications", key: 22 },
    { name: "Litigation", key: 23 },
    { name: "Scanning Unit", key: 24 },
    { name: "PS Secretariat", key: 25 },
    { name: "General Administration", key: 26 },
    { name: "Information Technology", key: 27 },
    { name: "Internal Audit", key: 28 },
    { name: "Human Resource Management Unit", key: 29 },
    { name: "Legislative Drafting Unit (CPC)", key: 30 },
    { name: "Records Management Unit", key: 31 },
    { name: "Law Revision Commission", key: 32 },
    { name: "Policy and Research Unit", key: 33 },
    { name: "Facilities Management Unit", key: 34 },
    { name: "Civil Child Abduction Unit", key: 35 },
    { name: "Library", key: 36 },
    { name: "Office of Child Rights", key: 37 },
    { name: "Office Management Unit", key: 38 },
    { name: "Finance and Accounts", key: 39 },
    { name: "Project Management Unit", key: 40 },
    { name: "Digitization Unit", key: 41 },
    { name: "DPS Secretariat", key: 42 },
    { name: "Anti-Terrorism Unit", key: 43 },
    { name: "Criminal Justice Unit", key: 44 },
    { name: "Process Review Team", key: 45 },
    { name: "AG Secretariat", key: 46 },
    { name: "Corp. Communications Unit", key: 47 },
    { name: "Central Authority Unit", key: 48 },
    { name: "International Law and Human Rights", key: 49 },
    { name: "Intellectual Property Office", key: 50 },
    { name: "Solicitor General Department", key: 51 },
    { name: "Information and Communciations Technology Unit", key: 52 },
    { name: "Equal Opportunity Commission", key: 53 },
    { name: "Monitoring and Evaluation", key: 54 },
    { name: "Vacation and After School Centre", key: 55 },
    { name: "Companies Registry", key: 56 },
    { name: "Chief State  Solicitor", key: 57 },
    { name: "Minister's Secretariat", key: 58 },
    { name: "Director of Public Prosecution", key: 59 },
    { name: "Legal Aid and Advisory Authority", key: 60 },
    { name: "Criminal law", key: 61 },
    { name: "Procurement unit", key: 62 },
];
